### ISSUE TITLE
Plains biome 256+

### ISSUE THREAD

**Issue by Tanjiraaaaa** [DeeChael/HigherNether#2]
![2024-06-27_19 56 05](https://github.com/DeeChael/HigherNether/assets/91242022/5879af6e-0ffe-440a-b78c-11aedbc4a2d9)
From what I've seen, this only appears ontop of a Nether Wastes biome.
I am using the Incendium mod, any ideas on how to fix this?

**Comment by Tanjiraaaaa** [comment]
I am currently using 1.20.6 btw

**Comment by Tanjiraaaaa** [comment]
![image](https://github.com/DeeChael/HigherNether/assets/91242022/d2ebaefd-a95f-4877-8a8a-a03c359ca679)
This isn't every mod I have installed but it is all of the mods related to the nether.

**Comment by Tanjiraaaaa** [comment]
The seed of my world is: 2489499807509984245
And the coords are: -1727 256+(308) 517

**Comment by Tanjiraaaaa** [comment]
The seed of my world is: 2489499807509984245
And the coords are: -1727 256+(308) 517

**Comment by DeeChael** [comment]
duplicated with #1
